### ISSUE TITLE
Request for new feature: run multiple replicates with different seeds and picks the best result

### ISSUE THREAD

**Issue by mvfki** [kharchenkolab/leidenAlg#16]
In the leiden.cpp source code, can we add another level of for loop to run it multiple times with the random number being updated? and after the while loop ends, access the quality or modularity so we can finally pick the best result. This is something that [Seurat's louvain implementation](https://github.com/satijalab/seurat/blob/master/src/ModularityOptimizer.cpp#L946) has and I figured this should also be helpful for running Leiden.

Thanks,
Yichen

**Comment by evanbiederstedt** [comment]
Hi @mvfki 

Thanks for the issue. 

It's a decent idea. I'm afraid I won't have the bandwidth to implement this myself. However, I've put a lab "help wanted" on the issue. If someone makes a pull request, I'll happily review. 

Thanks, Evan

**Comment by mvfki** [comment]
Thank you, Evan, for your fast response. That sounds great and I can do it recently. 

I wonder how soon it could be reflected on Cran if things go smoothly on my end. I had this request because I'm working on another package where our team would love a pure R (reticulate free) Leiden call, while I failed to find a wrapper package that has the feature I mentioned. We tried compiling the package with leidenalg and igraph source code placed in our repo and an Rcpp function customized. But I still think the cleanest way should be simply relying on a dependency package that works solely for Leiden clustering. Therefore, a Cran package with such a feature is highly desired. 

Best,
Yichen

**Comment by evanbiederstedt** [comment]
I may have misunderstood

The package is currently on CRAN: https://cran.r-project.org/web/packages/leidenAlg/index.html

You could create a this new feature as a function within this package, and I'll update this package with a new version on CRAN (citing your contributions). 

Or you could take the C++ code and wrappers and create your own package. 

Or try to call this via R, but I think you need to set the seed within C++.

**Comment by mvfki** [comment]
Sorry for the confusion. My hope would be to go with this one

> You could create a this new feature as a function within this package, and I'll update this package with a new version on CRAN (citing your contributions).

I tried the other options but still think it would be the cleanest solution if you are willing to help out.

**Comment by evanbiederstedt** [comment]
That's perfect @mvfki 

Please create a pull request, and I'll review. Thanks, Evan

**Comment by szhorvat** [comment]
Keep in mind that there is useful information in the fluctuations across several runs of stochastic community detection algorithms. Looking at a sample of results gives hints about whether there's actually a community structure, which is not always the case. Blindly choosing the highest modularity result, instead of considering the entire sample, hides this fact.

If you are going to use stochastic methods to improve modularity, there are more effective techniques than just taking the maximum of a random sample. See for example https://www.nature.com/articles/s41598-019-50739-3

**Comment by theAeon** [comment]
> Or try to call this via R, but I think you need to set the seed within C++.

CRAN check doesn't like this-my understanding is that the C++ seed is inherited from R's set.seed.

**Comment by evanbiederstedt** [comment]
> my understanding is that the C++ seed is inherited from R's set.seed.

You might be right, but I'd have to check. My point (which I think is right, but I won't have time to experiment) was rather that setting `set.seed()` will not inherently randomness in the C++ code. That needs to be specified as an argument in the function, which is precisely what this PR does: https://github.com/kharchenkolab/leidenAlg/pull/17

If CRAN has concerns, the function internally could unset the seed. That should be fine.

**Comment by theAeon** [comment]
FWIW everything I'm seeing on stackoverflow is saying that the best way to do this is to just pass the output of `get.seed` as an argument from R.

**Comment by evanbiederstedt** [comment]
https://stackoverflow.com/questions/43221681/changing-rs-seed-from-rcpp-to-guarantee-reproducibility

https://cran.r-project.org/doc/manuals/R-exts.html

> Compiled code should not call the system random number generators such as rand, drand48 and random[81](https://cran.r-project.org/doc/manuals/R-exts.html#FOOT81), but rather use the interfaces to R’s RNGs described in [Random number generation](https://cran.r-project.org/doc/manuals/R-exts.html#Random-numbers). In particular, if more than one package initializes a system RNG (e.g. via srand), they will interfere with each other.
Nor should the C++11 random number library be used, nor any other third-party random number generators such as those in GSL.

Hmm, fair enough.

**Comment by mvfki** [comment]
Since we've got the release with the update #17 , I guess we can close this now.

**Comment by evanbiederstedt** [comment]
**Note for future:**

Released in this version v1.1.1: https://github.com/kharchenkolab/leidenAlg/releases/tag/1.1.1
