### ISSUE TITLE
ImportError

### ISSUE THREAD

**Issue by Sa753** [kharchenkolab/leidenAlg#6]
Dear team,
I am trying to run infercnv which runs well till it gets to the step when it needs leidenalg. I installed leidenalg via pip install and it is installed but I consistently get an ImportError that leidenalg module is not found. So , I installed leindenAlg and loaded it successfully in R but I am still getting the same error that R can't see the package?.

Any suggestions from your side, please?.

I have asked leidenalg team and infercnv as well

Thanks

**Comment by pkharchenko** [comment]
Sounds like a potential issue with your environment. I am not used to pip installs for R, but can you check by launching R manually and trying running “library(leidenAlg)”

**Comment by evanbiederstedt** [comment]
Hi @Sa753 

You may be confused. The original C++ code had a python wrapper; see here: https://github.com/vtraag/leidenalg

That is the python module `leidenalg`, which you could install via pip. 

This is the R implementation of that algorithm. The authors were kind enough to reference this implementation in the README: https://github.com/vtraag/leidenalg#usage

Best, Evan
