### ISSUE TITLE
ModuleNotFoundError: No module named 'leidenalg'

### ISSUE THREAD

**Issue by howtofindme** [kharchenkolab/leidenAlg#8]
hi,
Sorry to interrupt you,but i ran into a issue when i run this code in R:
    mini_visium <- doLeidenCluster(gobject = mini_visium, 
                               resolution = 0.4, n_iterations = 1000) 

a problem occurs : 
Error in py_run_file_impl(file, local, convert) : 
  ModuleNotFoundError: No module named 'leidenalg'

Detailed traceback:
  File "<string>", line 10, in <module>
  File "D:\Win10 System\Documents\R\win-library\4.1\reticulate\python\rpytools\loader.py", line 44, in _import_hook
    level=level

So,i checked this :
![image](https://user-images.githubusercontent.com/72066151/158738342-41dde3b9-01b5-43b2-8d0d-3fd7090976c8.png)

And using conda, i found this:  leidenalg is there!!!
![image](https://user-images.githubusercontent.com/72066151/158738811-fbfa3f49-0257-4b0e-9dfd-3cc8e96e50f2.png)

And then i tried this : Although  leidenalg , pandas AND pillow is in my evrironment,but only pandas could be uesed.
![image](https://user-images.githubusercontent.com/72066151/158742932-66e17c48-9376-4e68-b69b-9d5cb5317c69.png)

Could you please help sovle this problem?

**Comment by evanbiederstedt** [comment]
Hi @howtofindme 

Thanks for the issue. 
Based on the function you're running `doLeidenCluster()`, I think you have the wrong GitHub repo. https://github.com/RubD/Giotto/blob/master/R/clustering.R#L41

You might want to open up this issue here: https://github.com/RubD/Giotto

Thanks, Evan
